// cams
export default {
  prefix: 'camsApi',
  namespace: 'CamsApi',
  url: 'https://centerapi.$1.shijizhongyun.com',
  list: {
    // 'cams-basicConfiguration': '/swagger/基础配置/swagger.json',
    // 'cams-airSignairLine': '/swagger/DDU菜单-签约航线管理/swagger.json',
    // 'cams-airPostCodeAirport': '/swagger/DDU菜单-邮编对应机场/swagger.json',
    // 'cams-airDDPDeliveryPlace': '/swagger/DDU菜单-DDP门对门交货地/swagger.json',
    // 'cams-airDDUDelivery': '/swagger/DDU菜单-DDU派送费/swagger.json',
    // 'cams-airCountryPostCode': '/swagger/DDU菜单-国家下拉邮编/swagger.json',
    // 'cams-airDDULocalFee': '/swagger/DDU菜单-DDU本地费/swagger.json',
    // 'cams-airDDUProduct':
    //   '/swagger/DDU%E8%8F%9C%E5%8D%95-%E4%BA%A7%E5%93%81%E7%AE%A1%E7%90%86/swagger.json', // DDU产品管理
    // 'cams-airDDUPriceFilter': '/swagger/DDU菜单-DDU批量价格过滤/swagger.json', // DDU菜单-DDU批量价格过滤 运价-DDU菜单管理
    // 'cams-freightRate': '/swagger/运价-保底毛利润/swagger.json',
    // 'cams-airDDU': '/swagger/运价-DDU菜单管理/swagger.json',
    // 'cams-airFreightInquiry': '/swagger/运价-空运运价查询/swagger.json',
    // 'cams-airFreightRate': '/swagger/运价-空运运价/swagger.json',
    // 'cams-config': '/swagger/工作单-工作单配置/swagger.json',
    // 'cams-airExportImport': '/swagger/工作单-空运进出口/swagger.json',
    // 'cams-workOrderBasic': '/swagger/工作单-基本信息/swagger.json',
    // 'cams-basicInfoSystemSetting': '/swagger/基础信息--系统设置/swagger.json',
    // 'cams-bSingleSalesman': '/swagger/基础信息--B单业务员/swagger.json',
    // 'cams-seaDDU': '/swagger/运价-海运运价-DDU整柜本地相关费用/swagger.json',
    // 'cams-seaFreightRate': '/swagger/运价-海运运价/swagger.json',
    // 'cams-basicInformation': '/swagger/基础信息/swagger.json',
    // 'cams-basicInformationTerritory': '/swagger/基础信息--区域/swagger.json',
    // 'cams-workorderSeaLclMblShare': '/swagger/工作单-海运拼箱进出口/swagger.json',
    // 'cams-workorderShippingLCLImportAndExport': '/swagger/工作单-海运拼箱整柜进出口/swagger.json',
    // 'cams-workorderSeaFclMblShare': '/swagger/工作单-海运整柜进出口/swagger.json',
    // 'cams-systemBaseTerritory': '/swagger/基础信息--其他/swagger.json',
    // 'cams-freightRatesEnquiry': '/swagger/运价-D条款询价/swagger.json',
    // 'cams-publicInterface': '/swagger/公共接口/swagger.json',
    // 'cams-seaEndPortRequire': '/swagger/海运档案/swagger.json',
    // 'cams-lcLAssembledPayableLocalCharges': '/swagger/海运管理-配置管理/swagger.json',
    // 'cams-airTransportation': '/swagger/空运管理-自动化配置/swagger.json',,
    // 'cams-billAuto': '/swagger/空运管理-提单自动化/swagger.json',
    // 'cams-relevantPrecautions': '/swagger/空运管理-相关注意事项/swagger.json',
    // 'cams-other': '/swagger/空运管理-其他/swagger.json',
    // 'cams-airfreightArchives': '/swagger/空运管理-空运档案/swagger.json',
    // 'cams-airFreightManagementBasicConfiguration': '/swagger/空运管理--基础配置/swagger.json',
    // 'cams-workOrderStatistics': '/swagger/工作单-工作单统计/swagger.json',
    // 'cams-workOrderNonConformanceRecords': '/swagger/工作单-不合规记录/swagger.json',
    // 'cams-workOrderShippingPublic': '/swagger/工作单-海运公共/swagger.json',
    // 'cams-workOrderStatusCard': '/swagger/工作单-状态卡/swagger.json',
    // 'cams-workOrderModifyInfo': '/swagger/工作单-工作单信息修改/swagger.json',
    // 'cams-workorderFlow': '/swagger/工作单-流程/swagger.json',
    // 'cams-workOrderReceipt': '/swagger/工作单-收据/swagger.json',
    // 'cams-wokOrderCommon': '/swagger/工作单-空海运公共/swagger.json',
    // 'cams-fmc': '/swagger/工作单-费用/swagger.json',
    // 'cams-role': '/swagger/工作单-报表-角色/swagger.json',
    // 'cams-reportAuthorization': '/swagger/工作单-报表-授权/swagger.json',
    // 'cams-Report': '/swagger/工作单-报表/swagger.json',
    // 'cams-charterPlaneFees': '/swagger/工作单-包机杂费/swagger.json',
    // 'cams-onekeyExportPDF': '/swagger/工作单-一键导出PDF/swagger.json',
    // 'cams-airReceivingRecord': '/swagger/工作单-收货记录/swagger.json',
    // 'cams-conditions': '/swagger/工作单-报表-条件/swagger.json',
    // 'cams-chatGroup': '/swagger/工作单-群组/swagger.json',
    // 'cams-airCostRelated': '/swagger/空运管理-费用相关/swagger.json',
    // 'cams-seaFclDeliveryNearPort': '/swagger/运价-整柜DDU菜单管理/swagger.json',
    // 'cams-Country': '/swagger/基础信息--国家/swagger.json',
    // 'cams-air-port-information-sheet': '/swagger/工作单-空运机场信息/swagger.json',
    // 'cams-Country': '/swagger/基础信息--国家/swagger.json',
    // 'cams-minimumFeeConfig': '/swagger/工作单-最低空运费配置/swagger.json',
    // 'cams-reversalWorkOrder': '/swagger/冲账工作单/swagger.json',
    // 'cams-mutualBooking': '/swagger/工作单-互订/swagger.json',
    // 'cams-triggerAirportData': '/swagger/工作单-机场数据的触发/swagger.json',
    // 'cams-airLineResource': '/swagger/平台管理--项目货-航线资源/swagger.json',
    // 'cams-shineBookingManagement': '/swagger/平台管理--项目货-Shine订舱管理/swagger.json',
    // 'cams-airTiktokBookingManagement': '/swagger/平台管理--项目货-Tiktok订舱管理/swagger.json',
    // 'cams-airBookingManagement': '/swagger/平台管理--项目货-订舱管理/swagger.json',
    // 'cams-airTemuBookingManagement': '/swagger/平台管理--项目货-Temu订舱管理/swagger.json',
    // 'cams-airPickupOrder': '/swagger/平台管理--项目货-提货订单/swagger.json',
    // 'cams-airportCompany': '/swagger/空运管理-空港所属公司/swagger.json',
    // 'cams-createOrderCommon': '/swagger/工作单-系统自动生成单和利润的计算/swagger.json',
    // 'cams-freightRateQuery': '/swagger/运价-DDU运价/swagger.json',
  },
}
