// 用户中心
export default {
  prefix: 'userApi',
  namespace: 'UserApi',
  url: `https://centerapi.$1.shijizhongyun.com`,
  list: {
    // 'user-user': '/swagger/用户/swagger.json',
    // 'user-role': '/swagger/角色/swagger.json',
    // 'user-auth': '/swagger/权限项/swagger.json',
    // 'user-code': {
    //   json: '/swagger/验证码/swagger.json',
    //   routes: ['/Captcha/GetCaptcha', '/Captcha/VerfiyCaptcha'],
    // },
    // 'user-menu': '/swagger/目录页面/swagger.json',
    // 'user-oAuth': '/swagger/身份认证/swagger.json',
    // 'user-system': '/swagger/子系统/swagger.json',
    // "user-service": "/swagger/外部UI调用服务/swagger.json",
    // "user-msgInfo": "/swagger/消息记录/swagger.json",
    // "user-employee": "/swagger/员工服务/swagger.json",
    // "user-taskInfo": "/swagger/任务中心/swagger.json",
    // "user-identity": "/swagger/岗位身份/swagger.json",
    // 'user-business': '/swagger/业务主体/swagger.json',
    // 'user-organize': '/swagger/组织/swagger.json',
    // 'user-position': '/swagger/岗位、岗位类型/swagger.json',
    // "user-userAuth": "/swagger/用户个人权限项/swagger.json",
    // "user-authAgent": "/swagger/权限授权转移/swagger.json",
    // "user-msgTemType": "/swagger/模板分类列表/swagger.json",
    // "user-background": "/swagger/首页背景图修改/swagger.json",
    // "user-dictionary": "/swagger/字典数据/swagger.json",
    // "user-machineCode": "/swagger/机器码/swagger.json",
    // "user-msgTemplate": "/swagger/消息模板/swagger.json",
    // "user-msgInstance": "/swagger/消息订阅实例/swagger.json",
    // "user-messageInfo": "/swagger/消息中心/swagger.json",
    // "user-authClassify": "/swagger/权限项分类/swagger.json",
    // 'user-businessRole': '/swagger/业务角色/swagger.json',
    // 'user-businessRole': {
    //   json: '/swagger/业务角色/swagger.json',
    //   routes: [],
    // },
    // "user-externalUser": "/swagger/外部用户接口/swagger.json",
    // 'user-externalUser': {
    //   json: '/swagger/外部用户接口/swagger.json',
    //   routes: [],
    // },
    // "user-companySystem": "/swagger/公司体系/swagger.json",
    // "user-staffGrouping": "/swagger/员工分组/swagger.json",
    // 'user-dataAuthConfig': '/swagger/数据权限配置/swagger.json',
    // "user-modifyTelPhone": "/swagger/修改手机号/swagger.json",
    // "user-userModifyPassword": "/swagger/用户修改密码操作/swagger.json",
    // 'user-dataAuthDefinedUser': '/swagger/自定义数据权限/swagger.json',
    // "user-msgSubscriptionService": "/swagger/消息订阅服务/swagger.json",
    // 'user-pageConfig': '/swagger/用户页面配置/swagger.json',
  },
}
